Repository equinor/webviz-subsurface, pull requests merged in 2021-12, with the labels that each got.

#863 Second bugfix on sensitivity comparison in VolumetricAnalysis
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
Labels: bug 🐛, next release 🚢

#868 Remove `CODEOWNERS`
  .github/CODEOWNERS
Labels: maintenance

#872 Fix pylint error breaking master
  webviz_subsurface/_components/parameter_filter.py
Labels: bug 🐛, CeeSol

#877 Fix issues with WellLogViewer prop changes
  CHANGELOG.md
  webviz_subsurface/plugins/_well_log_viewer/controllers/_well_controller.py
  webviz_subsurface/plugins/_well_log_viewer/utils/__init__.py
  webviz_subsurface/plugins/_well_log_viewer/utils/default_color_tables.py
  webviz_subsurface/plugins/_well_log_viewer/utils/xtgeo_well_log_to_json.py
  webviz_subsurface/plugins/_well_log_viewer/well_log_viewer.py
Labels: bug 🐛, next release 🚢

#878 Use regular numpy for all map statistic calculations
  webviz_subsurface/_models/surface_set_model.py
Labels: bug 🐛, next release 🚢

#889 Added `rel_file_pattern` argument to EnsembleSummaryProviderFactory methods
  CHANGELOG.md
  tests/unit_tests/provider_tests/test_ensemble_summary_provider.py
  webviz_subsurface/_providers/ensemble_summary_provider/_arrow_unsmry_import.py
  webviz_subsurface/_providers/ensemble_summary_provider/dev_compare_fmu_to_lazy_provider.py
  webviz_subsurface/_providers/ensemble_summary_provider/dev_provider_perf_testing.py
  webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py
Labels: enhancement 🚀

#867 New simulation time series plugin
  CHANGELOG.md
  setup.py
  webviz_subsurface/_utils/fanchart_plotting.py
  webviz_subsurface/_utils/statistics_plotting.py
  webviz_subsurface/_utils/vector_calculator.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/ensemble_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/graph_figure_builder_base.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/types/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_delta_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_vectors_accessor.py
  webviz_subsurface/plugins/_simulation_time_series/types/provider_set.py
  webviz_subsurface/plugins/_simulation_time_series/types/types.py
  webviz_subsurface/plugins/_simulation_time_series/utils/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/delta_ensemble_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/derived_ensemble_vectors_accessor_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/from_timeseries_cumulatives.py
  webviz_subsurface/plugins/_simulation_time_series/utils/history_vectors.py
  webviz_subsurface/plugins/_simulation_time_series/utils/provider_set_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/trace_line_shape.py
  webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
Labels: enhancement 🚀, CeeSol

#883 New SimulationTimeSeries Plugin: Statistics + realizations plot
  CHANGELOG.md
  webviz_subsurface/_datainput/xsection.py
  webviz_subsurface/_utils/colors.py
  webviz_subsurface/_utils/fanchart_plotting.py
  webviz_subsurface/_utils/statistics_plotting.py
  webviz_subsurface/plugins/_property_statistics/models/simulation_timeseries_model.py
  webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/ensemble_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/graph_figure_builder_base.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/types/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_delta_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_vectors_accessor.py
  webviz_subsurface/plugins/_simulation_time_series/types/provider_set.py
  webviz_subsurface/plugins/_simulation_time_series/types/types.py
  webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
  webviz_subsurface/plugins/_structural_uncertainty/figures/intersection.py
Labels: enhancement 🚀, CeeSol, next release 🚢

#888 Seismic misfit improvements
  CHANGELOG.md
  webviz_subsurface/plugins/_seismic_misfit.py
Labels: next release 🚢

#884 Parameter response tab in RFT plotter
  CHANGELOG.md
  webviz_subsurface/_figures/__init__.py
  webviz_subsurface/_figures/barchart.py
  webviz_subsurface/_figures/scatterplot.py
  webviz_subsurface/_utils/colors.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
  webviz_subsurface/plugins/_parameter_analysis/utils/colors.py
  webviz_subsurface/plugins/_rft_plotter/_business_logic.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/callbacks.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/parameter_response_callbacks.py
  webviz_subsurface/plugins/_rft_plotter/_figures/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_crossplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_errorplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_formation_figure.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_map_figure.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_misfit_figure.py
  webviz_subsurface/plugins/_rft_plotter/_layout.py
  webviz_subsurface/plugins/_rft_plotter/_processing.py
  webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
Labels: next release 🚢

#895 General improvements to VolumetricAnalysis
  CHANGELOG.md
  webviz_subsurface/_assets/css/inplace_volumes.css
  webviz_subsurface/_figures/px_figure.py
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/layout_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
  webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/fipfile_qc_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/tornado_view.py
Labels: enhancement 🚀, next release 🚢
