Repository equinor/webviz-subsurface, pull requests merged in 2021-09, with the labels that each got.

#749 Fix for single valued columns in `LinePlotterFMU`
  CHANGELOG.md
  webviz_subsurface/plugins/_line_plotter_fmu/controllers/build_figure.py
Labels: bug 🐛, next release 🚢

#747 Filter on OK in `ensemble_table_provider_factory`
  CHANGELOG.md
  webviz_subsurface/_providers/ensemble_table_provider_factory.py
Labels: next release 🚢

#753 Handle missing surfaces in PropertyStatistics and support changes in input format
  CHANGELOG.md
  webviz_subsurface/plugins/_property_statistics/controllers/property_delta_controller.py
  webviz_subsurface/plugins/_property_statistics/controllers/property_qc_controller.py
  webviz_subsurface/plugins/_property_statistics/controllers/property_response_controller.py
  webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
  webviz_subsurface/plugins/_property_statistics/property_statistics.py
  webviz_subsurface/plugins/_property_statistics/utils/surface.py
  webviz_subsurface/plugins/_property_statistics/views/main_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_delta_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_qc_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
  webviz_subsurface/plugins/_property_statistics/views/selector_view.py
Labels: bug 🐛, next release 🚢

#757 Prepare for release
  CHANGELOG.md
  setup.py
Labels: next release 🚢

#759 Add `useless-suppression` to `pylint` checks
  .pylintrc
  webviz_subsurface/_components/color_picker.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
  webviz_subsurface/_datainput/from_timeseries_cumulatives.py
  webviz_subsurface/_datainput/pvt_data.py
  webviz_subsurface/_datainput/units.py
  webviz_subsurface/_datainput/xsection.py
  webviz_subsurface/_private_plugins/surface_selector.py
  webviz_subsurface/ert_jobs/jobs.py
  webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
  webviz_subsurface/plugins/_inplace_volumes_onebyone.py
  webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
  webviz_subsurface/plugins/_parameter_correlation.py
  webviz_subsurface/plugins/_parameter_parallel_coordinates.py
  webviz_subsurface/plugins/_pvt_plot.py
  webviz_subsurface/plugins/_relative_permeability.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
  webviz_subsurface/plugins/_running_time_analysis_fmu.py
  webviz_subsurface/plugins/_segy_viewer.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/intersection_controller.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/uncertainty_table_controller.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/tornado_plotter_fmu.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
  webviz_subsurface/plugins/_well_completions.py
Labels: maintenance

#761 Store `xtgeo.RegularSurface` as bytestream
  CHANGELOG.md
  webviz_subsurface/_models/surface_set_model.py
Labels: next release 🚢

#765 Use correct inline/xline ranges for axes in ` SegyViewer` z-slice graph
  CHANGELOG.md
  webviz_subsurface/plugins/_segy_viewer.py
Labels: next release 🚢

#768 Adjust to latest `pylint`
  webviz_subsurface/_private_plugins/surface_selector.py
  webviz_subsurface/plugins/_disk_usage.py
  webviz_subsurface/plugins/_history_match.py
  webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
  webviz_subsurface/plugins/_line_plotter_fmu/figures/plotly_line_plot.py
  webviz_subsurface/plugins/_morris_plot.py
  webviz_subsurface/plugins/_parameter_analysis/utils/colors.py
  webviz_subsurface/plugins/_property_statistics/utils/colors.py
  webviz_subsurface/plugins/_pvt_plot.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
  webviz_subsurface/plugins/_subsurface_map.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
Labels: maintenance

#770 Support eclipse volumes in `VolumetricAnalysis`
  CHANGELOG.md
  setup.py
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
  webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
  webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
Labels: next release 🚢

#777 Added source and ensemble comparison to `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/_figures/px_figure.py
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/__init__.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
  webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
  webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
Labels: enhancement 🚀, next release 🚢

#784 Layout change Ensemble comparison tab `VolumetricAnalysis`
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
Labels: next release 🚢

#791 Ensure map bounds are updated when switching attribute in `SurfaceViewerFMU`
  CHANGELOG.md
  webviz_subsurface/plugins/_surface_viewer_fmu.py
Labels: bug 🐛, next release 🚢

#771 Grouptree plugin for network vizualisation
  setup.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_group_tree/__init__.py
  webviz_subsurface/plugins/_group_tree/controllers/__init__.py
  webviz_subsurface/plugins/_group_tree/controllers/controllers.py
  webviz_subsurface/plugins/_group_tree/group_tree.py
  webviz_subsurface/plugins/_group_tree/group_tree_data.py
  webviz_subsurface/plugins/_group_tree/views/__init__.py
  webviz_subsurface/plugins/_group_tree/views/filters_view.py
  webviz_subsurface/plugins/_group_tree/views/main_view.py
  webviz_subsurface/plugins/_group_tree/views/selections_view.py
Labels: enhancement 🚀, next release 🚢

#792 Update tests based on change in testdata set
  tests/conftest.py
  tests/unit_tests/model_tests/test_ensemble_set_model.py
  tests/unit_tests/provider_tests/test_ensemble_table_provider.py
Labels: Data input, maintenance

#794 Bugfix sensitivity run detection `ParametersModel`
  CHANGELOG.md
  webviz_subsurface/_models/parameter_model.py
Labels: next release 🚢

#802 Bugfixes `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
Labels: next release 🚢
