Repository equinor/webviz-subsurface, pull requests merged in 2021-07, with the labels that each got.

#711 Update required dash version to 1.20.0 due to dcc 1.16.0 dependency
  setup.py
Labels: bug 🐛, next release 🚢

#714 Use `pd.all()` in documented way
  webviz_subsurface/_components/tornado/_tornado_data.py
Labels: bug 🐛, maintenance, next release 🚢

#710 Removed `output` argument from ERT jobs (+ ensured output folder exists)
  tests/integration_tests/test_ert_jobs.py
  webviz_subsurface/ert_jobs/config_jobs/SMRY2ARROW
  webviz_subsurface/ert_jobs/config_jobs/WELL_CONNECTION_STATUS
  webviz_subsurface/ert_jobs/smry2arrow.py
  webviz_subsurface/ert_jobs/well_connection_status.py
Labels: bug 🐛, next release 🚢

#712 Fix callback issue `VolumetricAnalysis`
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
Labels: bug 🐛, next release 🚢

#718 Avoided recalculation of unique dates in `WellCompletions`
  webviz_subsurface/plugins/_well_completions.py
Labels: next release 🚢
