Repository equinor/webviz-subsurface, pull requests merged in 2021-06, with the labels that each got.

#646 Replaced dropdowns with `VectorSelector`
  CHANGELOG.md
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
Labels: next release 🚢

#662 `WellCompletion` history from summary data
  CHANGELOG.md
  setup.py
  tests/integration_tests/test_ert_jobs.py
  tests/unit_tests/plugin_tests/test_well_completions.py
  webviz_subsurface/_datainput/well_completions.py
  webviz_subsurface/ert_jobs/__init__.py
  webviz_subsurface/ert_jobs/config_jobs/EXPORT_CONNECTION_STATUS
  webviz_subsurface/ert_jobs/export_connection_status.py
  webviz_subsurface/ert_jobs/jobs.py
  webviz_subsurface/plugins/_well_completions.py
Labels: next release 🚢

#667 Standardize layout
  CHANGELOG.md
  webviz_subsurface/_components/parameter_filter.py
  webviz_subsurface/_components/tornado/tornado_widget.py
  webviz_subsurface/plugins/_assisted_history_matching_analysis.py
  webviz_subsurface/plugins/_bhp_qc.py
  webviz_subsurface/plugins/_disk_usage.py
  webviz_subsurface/plugins/_inplace_volumes_onebyone.py
  webviz_subsurface/plugins/_line_plotter_fmu/line_plotter_fmu.py
  webviz_subsurface/plugins/_line_plotter_fmu/views/__init__.py
  webviz_subsurface/plugins/_line_plotter_fmu/views/data_selectors_view.py
  webviz_subsurface/plugins/_line_plotter_fmu/views/plot_options_view.py
  webviz_subsurface/plugins/_line_plotter_fmu/views/plot_traces_view.py
  webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
  webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
  webviz_subsurface/plugins/_parameter_correlation.py
  webviz_subsurface/plugins/_parameter_parallel_coordinates.py
  webviz_subsurface/plugins/_parameter_response_correlation.py
  webviz_subsurface/plugins/_property_statistics/property_statistics.py
  webviz_subsurface/plugins/_property_statistics/views/main_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_delta_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_qc_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
  webviz_subsurface/plugins/_property_statistics/views/selector_view.py
  webviz_subsurface/plugins/_pvt_plot.py
  webviz_subsurface/plugins/_relative_permeability.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
  webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
  webviz_subsurface/plugins/_running_time_analysis_fmu.py
  webviz_subsurface/plugins/_segy_viewer.py
  webviz_subsurface/plugins/_structural_uncertainty/structural_uncertainty.py
  webviz_subsurface/plugins/_structural_uncertainty/views/intersection_and_map.py
  webviz_subsurface/plugins/_structural_uncertainty/views/intersection_data.py
  webviz_subsurface/plugins/_structural_uncertainty/views/map_data.py
  webviz_subsurface/plugins/_surface_with_grid_cross_section.py
  webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
  webviz_subsurface/plugins/_well_completions.py
Labels: next release 🚢

#669 Generic tornado plotter
  CHANGELOG.md
  setup.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/tornado_plotter_fmu.py
Labels: next release 🚢

#681 Tornadoplots, and further improvements to `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/_components/tornado/_tornado_table.py
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/__init__.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/export_data_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/layout_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/figures/px_figure.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/__init__.py
  webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
  webviz_subsurface/plugins/_volumetric_analysis/views/clientside_stores.py
  webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/filter_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/tornado_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/tornado_selections_view.py
  webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
Labels: enhancement 🚀, next release 🚢

#688 Remove duplicate title in `ReservoirSimulationTimeSeries`
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
Labels: next release 🚢

#689 Rename connection status to well connection status
  setup.py
  tests/integration_tests/test_ert_jobs.py
  webviz_subsurface/_datainput/well_completions.py
  webviz_subsurface/ert_jobs/config_jobs/WELL_CONNECTION_STATUS
  webviz_subsurface/ert_jobs/jobs.py
  webviz_subsurface/ert_jobs/well_connection_status.py
  webviz_subsurface/plugins/_well_completions.py
Labels: next release 🚢

#685 Added ERT forward model to convert from .UNSMRY to Arrow file format
  CHANGELOG.md
  setup.py
  tests/integration_tests/test_ert_jobs.py
  webviz_subsurface/ert_jobs/config_jobs/SMRY2ARROW
  webviz_subsurface/ert_jobs/jobs.py
  webviz_subsurface/ert_jobs/smry2arrow.py
Labels: next release 🚢

#682 Allow prereleases of Equinor theme in example Docker image
  .github/workflows/subsurface.yml
Labels: maintenance

#683 Add deprecation warning to `InplaceVolumesOneByOne`
  CHANGELOG.md
  webviz_subsurface/plugins/_inplace_volumes_onebyone.py
Labels: next release 🚢

#691 Remove `wcc.Frame` wrapper from `WellCompletions`
  webviz_subsurface/plugins/_well_completions.py
Labels: next release 🚢
