Repository equinor/webviz-subsurface, pull requests merged in 2021-11, with the labels that each got.

#833 Bugfixes to `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/views/tornado_view.py
Labels: bug 🐛, next release 🚢

#838 Fix timing issue in `AssistedHistoryMatchingAnalysis`
  CHANGELOG.md
  webviz_subsurface/plugins/_assisted_history_matching_analysis.py
Labels: bug 🐛, next release 🚢

#841 Bugfixes and improved hoverlabels for `Tornado component`
  CHANGELOG.md
  webviz_subsurface/_components/tornado/_tornado_bar_chart.py
  webviz_subsurface/_components/tornado/tornado_widget.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
Labels: bug 🐛, next release 🚢

#831 Deleted files related to `ert` jobs
  setup.py
  tests/integration_tests/test_ert_jobs.py
  webviz_subsurface/ert_jobs/__init__.py
  webviz_subsurface/ert_jobs/config_jobs/SMRY2ARROW
  webviz_subsurface/ert_jobs/config_jobs/WELL_CONNECTION_STATUS
  webviz_subsurface/ert_jobs/jobs.py
  webviz_subsurface/ert_jobs/smry2arrow.py
  webviz_subsurface/ert_jobs/well_connection_status.py
Labels: maintenance, next release 🚢

#832 Changed well connection status filetype to csv and updated docstring
  webviz_subsurface/_datainput/well_completions.py
  webviz_subsurface/plugins/_well_completions.py
Labels: maintenance, blocked ⏳, next release 🚢

#772 Add script for doing batch conversion of UNSMRY files to .arrow
  setup.py
  webviz_subsurface/smry2arrow_batch.py
Labels: enhancement 🚀, next release 🚢

#844 Seismic misfit improvements
  CHANGELOG.md
  webviz_subsurface/plugins/_seismic_misfit.py
Labels: enhancement 🚀, next release 🚢

#846 Removed `ert` from test dependencies
  setup.py
Labels: maintenance

#848 Updated target values in tests due to fixes in ecl 2.13.1
  tests/unit_tests/model_tests/test_ensemble_model.py
  tests/unit_tests/model_tests/test_ensemble_set_model.py
Labels: bug 🐛

#851 Added combined sensname-senscase column to `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/_models/parameter_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/views/filter_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
  webviz_subsurface/plugins/_volumetric_analysis/views/tornado_view.py
Labels: next release 🚢

#847 Refactoring `WellCompletions` code
  tests/unit_tests/plugin_tests/test_well_completions.py
  webviz_subsurface/plugins/_well_completions.py
  webviz_subsurface/plugins/_well_completions/__init__.py
  webviz_subsurface/plugins/_well_completions/_business_logic.py
  webviz_subsurface/plugins/_well_completions/_callbacks.py
  webviz_subsurface/plugins/_well_completions/_layout.py
  webviz_subsurface/plugins/_well_completions/_plugin.py
Labels: maintenance, next release 🚢

#721 Ensemble summary provider
  CHANGELOG.md
  setup.py
  tests/unit_tests/provider_tests/test_ensemble_summary_provider.py
  tests/unit_tests/provider_tests/test_ensemble_summary_provider_impl_arrow_lazy.py
  tests/unit_tests/provider_tests/test_ensemble_summary_provider_impl_arrow_presampled.py
  tests/unit_tests/provider_tests/test_ensemble_summary_provider_resampling.py
  webviz_subsurface/_providers/__init__.py
  webviz_subsurface/_providers/ensemble_summary_provider/__init__.py
  webviz_subsurface/_providers/ensemble_summary_provider/_arrow_unsmry_import.py
  webviz_subsurface/_providers/ensemble_summary_provider/_csv_import.py
  webviz_subsurface/_providers/ensemble_summary_provider/_dataframe_utils.py
  webviz_subsurface/_providers/ensemble_summary_provider/_field_metadata.py
  webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_lazy.py
  webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_presampled.py
  webviz_subsurface/_providers/ensemble_summary_provider/_resampling.py
  webviz_subsurface/_providers/ensemble_summary_provider/_table_utils.py
  webviz_subsurface/_providers/ensemble_summary_provider/dev_compare_fmu_to_lazy_provider.py
  webviz_subsurface/_providers/ensemble_summary_provider/dev_provider_perf_testing.py
  webviz_subsurface/_providers/ensemble_summary_provider/dev_resampling_perf_testing.py
  webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider.py
  webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py
Labels: next release 🚢

#842 Groups as leaf nodes in the `GroupTree` plugin
  CHANGELOG.md
  tests/unit_tests/plugin_tests/test_grouptree.py
  webviz_subsurface/plugins/_group_tree/group_tree.py
  webviz_subsurface/plugins/_group_tree/group_tree_data.py
Labels: enhancement 🚀, next release 🚢

#855 Allow mixing sensitivity and gen_kw ensembles in `ParametersModel`
  CHANGELOG.md
  webviz_subsurface/_models/parameter_model.py
Labels: next release 🚢

#856 Added sensitivity comparison to `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
Labels: enhancement 🚀, next release 🚢

#854 `RftPlotter` bug fixes and improvements
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_rft_plotter.py
  webviz_subsurface/plugins/_rft_plotter/_business_logic.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks.py
  webviz_subsurface/plugins/_rft_plotter/_errorplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_formation_figure.py
  webviz_subsurface/plugins/_rft_plotter/_layout.py
  webviz_subsurface/plugins/_rft_plotter/_map_figure.py
  webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
Labels: bug 🐛, maintenance, next release 🚢

#860 Regression fix in `VolumetricAnalysis`
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
Labels: bug 🐛

#865 Fix xtgeo/pylint linting issues
  webviz_subsurface/_datainput/well.py
  webviz_subsurface/_datainput/xsection.py
  webviz_subsurface/_models/well_set_model.py
  webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
Labels: bug 🐛
