Repository equinor/webviz-subsurface, pull requests merged in 2022-01, with the labels that each got.

#907 Fixed typing/mypy issues
  webviz_subsurface/_providers/ensemble_summary_provider/_resampling.py
  webviz_subsurface/_utils/simulation_timeseries.py
  webviz_subsurface/plugins/_line_plotter_fmu/controllers/build_figure.py
  webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
Labels: maintenance

#921 Use lowest valid provider realization for History Vectors in new `SimulationTimeSeries`
  CHANGELOG.md
  webviz_subsurface/plugins/_simulation_time_series/utils/history_vectors.py
Labels: bug 🐛, next release 🚢

#923 Unit tests new SimulationTimeSeries plugin
  tests/unit_tests/plugin_tests/test_simulation_time_series/__init__.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/mocks/__init__.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/mocks/derived_vectors_accessor_ensemble_summary_provider_mock.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/mocks/ensemble_summary_provider_dummy.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/mocks/provider_set_tests_ensemble_summary_provider_mock.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/__init__.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_delta_ensemble_vectors_accessor_impl.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_ensemble_vectors_accessor_impl.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_vector_accessor.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_provider_set.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/__init__.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_create_vector_traces_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_delta_ensemble_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_derived_ensemble_vectors_accessor_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_from_timeseries_cumulatives.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_history_vectors.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_provier_set_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_trace_line_shape.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_vector_statistics.py
  tests/unit_tests/utils_tests/test_dataframe_utils.py
  webviz_subsurface/_utils/dataframe_utils.py
  webviz_subsurface/_utils/fanchart_plotting.py
  webviz_subsurface/_utils/vector_calculator.py
  webviz_subsurface/plugins/_bhp_qc.py
  webviz_subsurface/plugins/_relative_permeability.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_formation_figure.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/ensemble_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_delta_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/from_timeseries_cumulatives.py
  webviz_subsurface/plugins/_simulation_time_series/utils/provider_set_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
  webviz_subsurface/plugins/_structural_uncertainty/figures/intersection.py
Labels: enhancement 🚀, CeeSol, next release 🚢

#934 Fix: correct labels in tornado when both cases are on same side of ref
  webviz_subsurface/_components/tornado/_tornado_bar_chart.py
Labels: next release 🚢

#932 `RftPlotter` fix: Handle correlate function returning `NaN` values
  CHANGELOG.md
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_rft_plotter/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_business_logic.py
  webviz_subsurface/plugins/_rft_plotter/_layout.py
  webviz_subsurface/plugins/_rft_plotter/_plugin.py
Labels: next release 🚢

#929 Don't skip SENSNAME ref if there multiple realizations in tornado
  CHANGELOG.md
  webviz_subsurface/_components/tornado/_tornado_data.py
Labels: next release 🚢

#924 Bugfixes and improvements to `ParameterFilter` and `ParameterAnalysis`
  CHANGELOG.md
  tests/integration_tests/test_parameter_filter.py
  webviz_subsurface/_components/parameter_filter.py
  webviz_subsurface/_models/parameter_model.py
  webviz_subsurface/plugins/_line_plotter_fmu/line_plotter_fmu.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
  webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
  webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
  webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
Labels: next release 🚢

#935 Deprecate `ReservoirSimulationTimeSeries`
  CHANGELOG.md
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
Labels: next release 🚢

#939 Bugfix in `ParameterFilter`
  webviz_subsurface/_components/parameter_filter.py
Labels: bug 🐛

#937 Fix hover info for observation trace new SimulationTimeSeries plugin
  CHANGELOG.md
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_create_vector_traces_utils.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
  webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py
Labels: bug 🐛

#947 Update according to new `black` version
  setup.py
  webviz_subsurface/_abbreviations/number_formatting.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
  webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
  webviz_subsurface/_models/surface_leaflet_model.py
  webviz_subsurface/plugins/_disk_usage.py
  webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
  webviz_subsurface/plugins/_pvt_plot.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_crossplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_figures/_map_figure.py
Labels: maintenance
