Repository equinor/webviz-subsurface, pull requests merged in 2022-09, with the labels that each got.

#1080 `GroupTree` to WLF
  CHANGELOG.md
  tests/unit_tests/plugin_tests/test_grouptree.py
  webviz_subsurface/plugins/_group_tree/_callbacks.py
  webviz_subsurface/plugins/_group_tree/_layout.py
  webviz_subsurface/plugins/_group_tree/_plugin.py
  webviz_subsurface/plugins/_group_tree/_types.py
  webviz_subsurface/plugins/_group_tree/_utils/__init__.py
  webviz_subsurface/plugins/_group_tree/_utils/_ensemble_group_tree_data.py
  webviz_subsurface/plugins/_group_tree/_views/__init__.py
  webviz_subsurface/plugins/_group_tree/_views/_group_tree_view/__init__.py
  webviz_subsurface/plugins/_group_tree/_views/_group_tree_view/_view.py
  webviz_subsurface/plugins/_group_tree/_views/_group_tree_view/_view_element.py
Labels: WLF

#1058 New implementation of the `WellCompletion` plugin (with WLF).
  CHANGELOG.md
  setup.py
  webviz_subsurface/_models/__init__.py
  webviz_subsurface/_models/stratigraphy_model.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_well_completion/__init__.py
  webviz_subsurface/plugins/_well_completion/_plugin.py
  webviz_subsurface/plugins/_well_completion/_utils/__init__.py
  webviz_subsurface/plugins/_well_completion/_utils/_well_completion_data_model.py
  webviz_subsurface/plugins/_well_completion/_views/__init__.py
  webviz_subsurface/plugins/_well_completion/_views/_well_completion_view/__init__.py
  webviz_subsurface/plugins/_well_completion/_views/_well_completion_view/_view.py
  webviz_subsurface/plugins/_well_completion/_views/_well_completion_view/_view_element.py
  webviz_subsurface/plugins/_well_completions/_plugin.py
Labels: WLF

#1089 Well analysis trail
  CHANGELOG.md
  webviz_subsurface/plugins/_well_analysis/_callbacks/__init__.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_control_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_overview_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_figures/__init__.py
  webviz_subsurface/plugins/_well_analysis/_layout/__init__.py
  webviz_subsurface/plugins/_well_analysis/_layout/clientside_stores.py
  webviz_subsurface/plugins/_well_analysis/_layout/main_layout.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_control_layout.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_overview_layout.py
  webviz_subsurface/plugins/_well_analysis/_plugin.py
  webviz_subsurface/plugins/_well_analysis/_types.py
  webviz_subsurface/plugins/_well_analysis/_utils/__init__.py
  webviz_subsurface/plugins/_well_analysis/_utils/_ensemble_well_analysis_data.py
  webviz_subsurface/plugins/_well_analysis/_views/__init__.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_control_view/__init__.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_control_view/_utils/__init__.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_control_view/_utils/_well_control_figure.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_control_view/_view.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_control_view/_view_element.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/__init__.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_utils/__init__.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_utils/_well_overview_figure.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_view.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_view_element.py
Labels: WLF

#1078 Pvt trail
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_pvt_plot.py
  webviz_subsurface/plugins/_pvt_plot.py
  webviz_subsurface/plugins/_pvt_plot/__init__.py
  webviz_subsurface/plugins/_pvt_plot/_plugin.py
  webviz_subsurface/plugins/_pvt_plot/_views/__init__.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/__init__.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_settings/__init__.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_settings/_data_settings.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_settings/_view_settings.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_utils/__init__.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_utils/_plot_utils.py
  webviz_subsurface/plugins/_pvt_plot/_views/_pvt/_view.py
Labels: WLF

#1092 Tornado plotter
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_tornado_plotter_fmu.py
  webviz_subsurface/_components/tornado/_tornado_bar_chart.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/callbacks.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/_error.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/_plugin.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/shared_settings/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/shared_settings/_filters.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/shared_settings/_selectors.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/shared_settings/_view_settings.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/tornado_plotter_fmu.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/plot_view/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/plot_view/_plot_view.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/plot_view/view_elements/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/plot_view/view_elements/plot.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/table_view/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/table_view/_table_view.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/table_view/view_elements/__init__.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/table_view/view_elements/table.py
Labels: WLF

#1117 Fix mypy errors in Tornado plot
  webviz_subsurface/_components/tornado/_tornado_bar_chart.py
  webviz_subsurface/_components/tornado/_tornado_data.py
  webviz_subsurface/_components/tornado/tornado_widget.py
  webviz_subsurface/plugins/_tornado_plotter_fmu/views/table_view/_table_view.py
Labels: next release 🚢

#1114 Minor fixes to `MapViewerFMU`
  CHANGELOG.md
  webviz_subsurface/_providers/ensemble_surface_provider/surface_server.py
  webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
  webviz_subsurface/plugins/_map_viewer_fmu/layout.py
  webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py
Labels: next release 🚢

#1116 Fix `pandas` `FutureWarnings`
  webviz_subsurface/_components/tornado/_tornado_data.py
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
  webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
Labels: next release 🚢

#1083 Parameter vs parameter
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_parameter_correlation.py
  tests/integration_tests/test_parameter_corr.py
  webviz_subsurface/plugins/_parameter_correlation.py
  webviz_subsurface/plugins/_parameter_correlation/__init__.py
  webviz_subsurface/plugins/_parameter_correlation/_error.py
  webviz_subsurface/plugins/_parameter_correlation/_plugin.py
  webviz_subsurface/plugins/_parameter_correlation/_plugin_ids.py
  webviz_subsurface/plugins/_parameter_correlation/views/__init__.py
  webviz_subsurface/plugins/_parameter_correlation/views/parameter_plot/__init__.py
  webviz_subsurface/plugins/_parameter_correlation/views/parameter_plot/_parameter_plot.py
  webviz_subsurface/plugins/_parameter_correlation/views/parameter_plot/settings/__init__.py
  webviz_subsurface/plugins/_parameter_correlation/views/parameter_plot/settings/_parameter_settings.py
Labels: next release 🚢, WLF

#1085 `ProdMisfit` moved to WLF
  CHANGELOG.md
  webviz_subsurface/plugins/_prod_misfit/_callbacks.py
  webviz_subsurface/plugins/_prod_misfit/_layout.py
  webviz_subsurface/plugins/_prod_misfit/_plugin.py
  webviz_subsurface/plugins/_prod_misfit/_plugin_ids.py
  webviz_subsurface/plugins/_prod_misfit/shared_settings/__init__.py
  webviz_subsurface/plugins/_prod_misfit/shared_settings/_filter.py
  webviz_subsurface/plugins/_prod_misfit/view_elements/__init__.py
  webviz_subsurface/plugins/_prod_misfit/view_elements/_graph.py
  webviz_subsurface/plugins/_prod_misfit/views/__init__.py
  webviz_subsurface/plugins/_prod_misfit/views/_production_misfit_per_real.py
  webviz_subsurface/plugins/_prod_misfit/views/_view_functions.py
  webviz_subsurface/plugins/_prod_misfit/views/_well_production_coverage.py
  webviz_subsurface/plugins/_prod_misfit/views/_well_production_heatmap.py
Labels: next release 🚢, WLF

#1061 Do not use pandas dataframe as argument to webvizstore decorated function
  CHANGELOG.md
  webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
  webviz_subsurface/plugins/_property_statistics/property_statistics.py
  webviz_subsurface/plugins/_property_statistics/utils/surface.py
Labels: next release 🚢

#1113 `RftPlotter` to WLF
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_rft_plotter.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/callbacks.py
  webviz_subsurface/plugins/_rft_plotter/_callbacks/parameter_response_callbacks.py
  webviz_subsurface/plugins/_rft_plotter/_layout.py
  webviz_subsurface/plugins/_rft_plotter/_plugin.py
  webviz_subsurface/plugins/_rft_plotter/_reusable_settings.py
  webviz_subsurface/plugins/_rft_plotter/_reusable_view_element.py
  webviz_subsurface/plugins/_rft_plotter/_types.py
  webviz_subsurface/plugins/_rft_plotter/_utils/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_utils/_formation_figure.py
  webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py
  webviz_subsurface/plugins/_rft_plotter/_views/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_settings/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_settings/_formation_plot_settings.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_settings/_map_settings.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_utils/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_utils/_map_figure.py
  webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_view.py
  webviz_subsurface/plugins/_rft_plotter/_views/_misfit_per_real_view/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_misfit_per_real_view/_settings.py
  webviz_subsurface/plugins/_rft_plotter/_views/_misfit_per_real_view/_utils/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_misfit_per_real_view/_utils/_misfit_per_real_figure.py
  webviz_subsurface/plugins/_rft_plotter/_views/_misfit_per_real_view/_view.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_options.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_parameter_filter.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_selections.py
  webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_view.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_settings/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_settings/_selections.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_settings/_size_color_settings.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_utils/__init__.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_utils/_crossplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_utils/_errorplot_figure.py
  webviz_subsurface/plugins/_rft_plotter/_views/_sim_vs_obs_view/_view.py
Labels: next release 🚢, WLF
