Repository equinor/webviz-subsurface, pull requests merged in 2022-02, with the labels that each got.

#940 User defined vector definition in SimulationTimeSeries plugin
  CHANGELOG.md
  tests/unit_tests/abbreviations_tests/__init__.py
  tests/unit_tests/abbreviations_tests/test_reservoir_simulation.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_delta_ensemble_vectors_accessor_impl.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_ensemble_vectors_accessor_impl.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_create_vector_traces_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_from_timeseries_cumulatives.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_provier_set_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_trace_line_shape.py
  webviz_subsurface/__init__.py
  webviz_subsurface/_abbreviations/abbreviation_data/reservoir_simulation_vectors.json
  webviz_subsurface/_abbreviations/reservoir_simulation.py
  webviz_subsurface/_utils/user_defined_vector_definitions.py
  webviz_subsurface/_utils/vector_calculator.py
  webviz_subsurface/_utils/vector_selector.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
  webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_delta_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_vectors_accessor.py
  webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/from_timeseries_cumulatives.py
  webviz_subsurface/plugins/_simulation_time_series/utils/provider_set_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/trace_line_shape.py
Labels: enhancement 🚀, CeeSol

#951 Delta relative to date within ensemble `SimulationTimeSeries`
  CHANGELOG.md
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_types/test_derived_vector_accessor.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_dataframe_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_datetime_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_derived_ensemble_vectors_accessor_utils.py
  webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_delta_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/derived_ensemble_vectors_accessor_impl.py
  webviz_subsurface/plugins/_simulation_time_series/types/provider_set.py
  webviz_subsurface/plugins/_simulation_time_series/utils/dataframe_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/datetime_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/derived_ensemble_vectors_accessor_utils.py
  webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
Labels: enhancement 🚀, CeeSol

#956 Add list of vectors as user input for `SimulationTimeSeries`
  CHANGELOG.md
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
Labels: enhancement 🚀

#960 Replace VectorCalculator modal with draggable dialog in SimulationTimeSeries
  webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
Labels: enhancement 🚀

#961 Improve error message when there are zero valid realizations
  CHANGELOG.md
  webviz_subsurface/__init__.py
Labels: next release 🚢

#958 Disable rangeslider marks in cross-section plugins
  CHANGELOG.md
  webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
  webviz_subsurface/plugins/_surface_with_grid_cross_section.py
  webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
Labels: next release 🚢

#972 Two bugfixes in `VolumetricAnalysis`
  CHANGELOG.md
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
  webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
Labels: bug 🐛, next release 🚢

#965 Allow filtered subset of surface names for multiple attributes in `StructuralUncertainty`
  CHANGELOG.md
  webviz_subsurface/plugins/_structural_uncertainty/structural_uncertainty.py
Labels: next release 🚢

#970 Replace modals with `wcc.Dialog` in `StructuralUncertainty`
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_structural_uncertainty.py
  webviz_subsurface/_assets/css/structural_uncertainty.css
  webviz_subsurface/plugins/_structural_uncertainty/controllers/__init__.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/dialog_controller.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/modal_controller.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/realization_filter_controller.py
  webviz_subsurface/plugins/_structural_uncertainty/controllers/uncertainty_table_controller.py
  webviz_subsurface/plugins/_structural_uncertainty/structural_uncertainty.py
  webviz_subsurface/plugins/_structural_uncertainty/views/__init__.py
  webviz_subsurface/plugins/_structural_uncertainty/views/dialog.py
  webviz_subsurface/plugins/_structural_uncertainty/views/intersection_and_map.py
  webviz_subsurface/plugins/_structural_uncertainty/views/intersection_data.py
  webviz_subsurface/plugins/_structural_uncertainty/views/map_data.py
  webviz_subsurface/plugins/_structural_uncertainty/views/modal.py
  webviz_subsurface/plugins/_structural_uncertainty/views/realization_filter.py
  webviz_subsurface/plugins/_structural_uncertainty/views/uncertainty_table.py
Labels: next release 🚢

#976 Handle covisualizations of static and dynamic maps
  webviz_subsurface/_providers/ensemble_surface_provider/_provider_impl_file.py
Labels: bug 🐛, next release 🚢

#977 Handle missing well picks
  webviz_subsurface/plugins/_map_viewer_fmu/_tmp_well_pick_provider.py
Labels: bug 🐛, next release 🚢
