Repository equinor/webviz-subsurface, pull requests merged in 2022-05, with the labels that each got.

#1032 Fix new `pylint` and `dash` test error
  webviz_subsurface/plugins/_structural_uncertainty/views/map_data.py
  webviz_subsurface/plugins/_swatinit_qc/_figures.py
  webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
Labels: maintenance

#897 Add Python 3.10 to CI
  .github/workflows/subsurface.yml
  README.md
Labels: maintenance

#1017 `SeismicMisfit` - support new polygon header standard
  CHANGELOG.md
  webviz_subsurface/plugins/_seismic_misfit.py
Labels: maintenance, next release 🚢

#1030 New data provider in `ParameterResponseCorrelation`
  CHANGELOG.md
  webviz_subsurface/_providers/__init__.py
  webviz_subsurface/_providers/ensemble_summary_provider/utils.py
  webviz_subsurface/plugins/_parameter_response_correlation.py
Labels: next release 🚢

#1020 `WellAnalysis` improvements
  CHANGELOG.md
  tests/unit_tests/model_tests/test_well_attributes_model.py
  webviz_subsurface/_models/gruptree_model.py
  webviz_subsurface/_models/well_attributes_model.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_control_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_overview_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_ensemble_well_analysis_data.py
  webviz_subsurface/plugins/_well_analysis/_figures/well_control_figure.py
  webviz_subsurface/plugins/_well_analysis/_figures/well_overview_figure.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_control_layout.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_overview_layout.py
  webviz_subsurface/plugins/_well_analysis/_plugin.py
  webviz_subsurface/plugins/_well_analysis/_types.py
Labels: next release 🚢

#1041 Increased maximum number of selected vectors in `SimulationTimeSeries`
  CHANGELOG.md
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
Labels: next release 🚢

#1035 Remove `pydeck` dependency
  CHANGELOG.md
  setup.py
  webviz_subsurface/_components/deckgl_map/__init__.py
  webviz_subsurface/_components/deckgl_map/types/__init__.py
  webviz_subsurface/_components/deckgl_map/types/deckgl_props.py
  webviz_subsurface/plugins/_map_viewer_fmu/_layer_model.py
  webviz_subsurface/plugins/_map_viewer_fmu/_types.py
  webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
  webviz_subsurface/plugins/_map_viewer_fmu/layout.py
Labels: next release 🚢

#1028 `BhpQc` - Read from `.arrow` files instead of `.UNSMRY` files
  CHANGELOG.md
  webviz_subsurface/plugins/_bhp_qc.py
Labels: Data input, next release 🚢

#1037 Add color tables to `MapViewer`
  CHANGELOG.md
  webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
  webviz_subsurface/plugins/_map_viewer_fmu/color_tables.py
  webviz_subsurface/plugins/_map_viewer_fmu/layout.py
  webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py
Labels: next release 🚢
