Repository equinor/webviz-subsurface, pull requests merged in 2022-10, with the labels that each got.

#1121 Fix `callback_typecheck` error for `wcc.Dialog` prop in `SimulationTimeSeries`
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_time_series.py
Labels: bug 🐛, next release 🚢

#1128 Fix `pandas` `FutureWarnings`
  webviz_subsurface/_datainput/pvt_data.py
  webviz_subsurface/plugins/_disk_usage.py
Labels: maintenance, next release 🚢

#1129 Fix `ConversionError` in `callback_typecheck`.
  webviz_subsurface/plugins/_well_analysis/_plugin.py
  webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_view.py
Labels: next release 🚢

#1138 More flexibility in `GroupTree`
  .github/workflows/subsurface.yml
  CHANGELOG.md
  tests/data/gruptree.csv
  tests/unit_tests/model_tests/test_gruptree_model.py
  tests/unit_tests/plugin_tests/test_grouptree.py
  webviz_subsurface/_models/gruptree_model.py
  webviz_subsurface/plugins/_group_tree/_plugin.py
  webviz_subsurface/plugins/_group_tree/_types.py
  webviz_subsurface/plugins/_group_tree/_utils/_ensemble_group_tree_data.py
Labels: next release 🚢
