Repository equinor/webviz-subsurface, pull requests merged in 2022-04, with the labels that each got.

#1001 Fix issues with just one parameter and for aggregated data in `ParameterResponseCorrelation`
  webviz_subsurface/plugins/_parameter_response_correlation.py
Labels: bug 🐛, next release 🚢

#938 New `ProdMisfit` plugin
  CHANGELOG.md
  setup.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_prod_misfit/__init__.py
  webviz_subsurface/plugins/_prod_misfit/_callbacks.py
  webviz_subsurface/plugins/_prod_misfit/_layout.py
  webviz_subsurface/plugins/_prod_misfit/_plugin.py
  webviz_subsurface/plugins/_prod_misfit/utils/__init__.py
  webviz_subsurface/plugins/_prod_misfit/utils/make_dataframes.py
  webviz_subsurface/plugins/_prod_misfit/utils/make_figures.py
Labels: enhancement 🚀, next release 🚢

#1013 Expose surface folder as an argument in `MapViewerFMU`
  CHANGELOG.md
  webviz_subsurface/_providers/ensemble_surface_provider/_surface_discovery.py
  webviz_subsurface/_providers/ensemble_surface_provider/ensemble_surface_provider_factory.py
  webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py
Labels: next release 🚢

#1014 Various bugfixes
  CHANGELOG.md
  webviz_subsurface/_models/inplace_volumes_model.py
  webviz_subsurface/plugins/_bhp_qc.py
  webviz_subsurface/plugins/_parameter_response_correlation.py
  webviz_subsurface/plugins/_swatinit_qc/_business_logic.py
  webviz_subsurface/plugins/_swatinit_qc/_figures.py
  webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
Labels: bug 🐛, next release 🚢
