Repository equinor/webviz-subsurface, pull requests merged in 2022-03, with the labels that each got.

#975 Fix documentation in MapViewer
  webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py
Labels: bug 🐛, next release 🚢

#980 Deprecate `SurfaceViewerFMU`
  CHANGELOG.md
  webviz_subsurface/plugins/_surface_viewer_fmu.py
Labels: maintenance, next release 🚢

#985 Update `WellLogViewer` data format to latest version
  CHANGELOG.md
  webviz_subsurface/plugins/_well_log_viewer/utils/xtgeo_well_log_to_json.py
Labels: bug 🐛, next release 🚢

#981 Well analysis plugin
  CHANGELOG.md
  setup.py
  webviz_subsurface/_models/__init__.py
  webviz_subsurface/_models/gruptree_model.py
  webviz_subsurface/_utils/colors.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_well_analysis/__init__.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/__init__.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_control_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_callbacks/well_overview_callbacks.py
  webviz_subsurface/plugins/_well_analysis/_ensemble_well_analysis_data.py
  webviz_subsurface/plugins/_well_analysis/_figures/__init__.py
  webviz_subsurface/plugins/_well_analysis/_figures/well_control_figure.py
  webviz_subsurface/plugins/_well_analysis/_figures/well_overview_figure.py
  webviz_subsurface/plugins/_well_analysis/_layout/__init__.py
  webviz_subsurface/plugins/_well_analysis/_layout/clientside_stores.py
  webviz_subsurface/plugins/_well_analysis/_layout/main_layout.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_control_layout.py
  webviz_subsurface/plugins/_well_analysis/_layout/well_overview_layout.py
  webviz_subsurface/plugins/_well_analysis/_plugin.py
Labels: next release 🚢

#991 Update according to latest `pylint`
  webviz_subsurface/_providers/ensemble_fault_polygons_provider/ensemble_fault_polygons_provider.py
  webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider.py
  webviz_subsurface/_providers/ensemble_surface_provider/ensemble_surface_provider.py
  webviz_subsurface/_providers/well_provider/well_provider.py
  webviz_subsurface/_utils/simulation_timeseries.py
  webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
  webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
  webviz_subsurface/plugins/_simulation_time_series/_property_serialization/graph_figure_builder_base.py
Labels: maintenance, next release 🚢

#989 Place `VectorCalculator` in `Div` with fixed height
  webviz_subsurface/plugins/_simulation_time_series/_layout.py
Labels: enhancement 🚀, next release 🚢

#987 New Water Initialization QC plugin `SwatinitQC`
  CHANGELOG.md
  setup.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_swatinit_qc/__init__.py
  webviz_subsurface/plugins/_swatinit_qc/_business_logic.py
  webviz_subsurface/plugins/_swatinit_qc/_callbacks.py
  webviz_subsurface/plugins/_swatinit_qc/_figures.py
  webviz_subsurface/plugins/_swatinit_qc/_layout.py
  webviz_subsurface/plugins/_swatinit_qc/_markdown.py
  webviz_subsurface/plugins/_swatinit_qc/_plugin.py
Labels: enhancement 🚀, next release 🚢

#988 Arrow support and other improvements to `ParameterAnalysis` and `PropertyStatistics`
  CHANGELOG.md
  tests/integration_tests/plugin_tests/test_parameter_analysis.py
  tests/integration_tests/plugin_tests/test_property_statistics.py
  webviz_subsurface/_figures/__init__.py
  webviz_subsurface/_figures/px_figure.py
  webviz_subsurface/_figures/scatterplot.py
  webviz_subsurface/_figures/timeseries_figure.py
  webviz_subsurface/_utils/dataframe_utils.py
  webviz_subsurface/_utils/datetime_utils.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
  webviz_subsurface/plugins/_parameter_analysis/data_loaders/__init__.py
  webviz_subsurface/plugins/_parameter_analysis/models/__init__.py
  webviz_subsurface/plugins/_parameter_analysis/models/ensemble_timeseries_datamodel.py
  webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
  webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
  webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
  webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
  webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
  webviz_subsurface/plugins/_property_statistics/controllers/property_delta_controller.py
  webviz_subsurface/plugins/_property_statistics/controllers/property_response_controller.py
  webviz_subsurface/plugins/_property_statistics/data_loaders/__init__.py
  webviz_subsurface/plugins/_property_statistics/models/__init__.py
  webviz_subsurface/plugins/_property_statistics/models/ensemble_timeseries_datamodel.py
  webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
  webviz_subsurface/plugins/_property_statistics/models/simulation_timeseries_model.py
  webviz_subsurface/plugins/_property_statistics/property_statistics.py
  webviz_subsurface/plugins/_property_statistics/views/main_view.py
  webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
  webviz_subsurface/plugins/_property_statistics/views/selector_view.py
Labels: next release 🚢

#986 Avoid copying surfaces when using MapViewerFMU in non-portable mode
  CHANGELOG.md
  webviz_subsurface/_providers/ensemble_surface_provider/_provider_impl_file.py
  webviz_subsurface/_providers/ensemble_surface_provider/dev_experiments.py
  webviz_subsurface/_providers/ensemble_surface_provider/ensemble_surface_provider_factory.py
Labels: next release 🚢

#996 Bugfix `VolumetricAnalysis` - tornados hidden if both dynamic and static sources
  CHANGELOG.md
  webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
Labels: bug 🐛

#995 Add backwards compatibility for older portables using `ParameterAnalysis` and `PropertyStatistic`
  webviz_subsurface/plugins/_parameter_analysis/data_loaders/__init__.py
  webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
  webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
  webviz_subsurface/plugins/_property_statistics/data_loaders/__init__.py
  webviz_subsurface/plugins/_property_statistics/models/simulation_timeseries_model.py
  webviz_subsurface/plugins/_property_statistics/property_statistics.py
Labels: bug 🐛
