Repository equinor/webviz-subsurface, pull requests merged in 2022-11, with the labels that each got.

#1152 `GroupTree`: Improved terminal_node filtering
  .github/workflows/subsurface.yml
  webviz_subsurface/_models/gruptree_model.py
Labels: next release 🚢

#1155 Set `implicit_optional=True` for `mypy`
  .github/workflows/subsurface.yml
  mypy.ini
Labels: enhancement 🚀

#1153 Replace wcc.LabeledContainer with wcc.Selectors for `Delta Ensembles` in `SimulationTimeSeries`
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_ensembles.py
Labels: enhancement 🚀

#994 CO₂ migration plugin
  setup.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_co2_leakage/__init__.py
  webviz_subsurface/plugins/_co2_leakage/_error.py
  webviz_subsurface/plugins/_co2_leakage/_plugin.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/__init__.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/co2volume.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/color_tables.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/fault_polygons.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/generic.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/initialization.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/plume_extent.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/surface_publishing.py
  webviz_subsurface/plugins/_co2_leakage/views/__init__.py
  webviz_subsurface/plugins/_co2_leakage/views/mainview/__init__.py
  webviz_subsurface/plugins/_co2_leakage/views/mainview/mainview.py
  webviz_subsurface/plugins/_co2_leakage/views/mainview/settings.py
Labels: next release 🚢

#1111 Grid viewer fmu
  CHANGELOG.md
  setup.py
  webviz_subsurface/_providers/ensemble_grid_provider/__init__.py
  webviz_subsurface/_providers/ensemble_grid_provider/_egrid_file_discovery.py
  webviz_subsurface/_providers/ensemble_grid_provider/_roff_file_discovery.py
  webviz_subsurface/_providers/ensemble_grid_provider/_xtgeo_to_vtk_explicit_structured_grid.py
  webviz_subsurface/_providers/ensemble_grid_provider/ensemble_grid_provider.py
  webviz_subsurface/_providers/ensemble_grid_provider/ensemble_grid_provider_factory.py
  webviz_subsurface/_providers/ensemble_grid_provider/grid_viz_service.py
  webviz_subsurface/_providers/ensemble_grid_provider/provider_impl_egrid.py
  webviz_subsurface/_providers/ensemble_grid_provider/provider_impl_roff.py
  webviz_subsurface/plugins/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/_layout_elements.py
  webviz_subsurface/plugins/_grid_viewer_fmu/_plugin.py
  webviz_subsurface/plugins/_grid_viewer_fmu/_types.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/_view_3d.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/settings/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/settings/_color_scale.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/settings/_data_selection.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/settings/_grid_filter.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/settings/_settings.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/view_elements/__init__.py
  webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/view_elements/_vtk_view_3d_element.py
Labels: next release 🚢

#1161 Remove direct import from `SimulationTimeSeries` utilities
  tests/unit_tests/mocks/__init__.py
  tests/unit_tests/mocks/ensemble_summary_provider_dummy.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/mocks/derived_vectors_accessor_ensemble_summary_provider_mock.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_delta_ensemble_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_derived_ensemble_vectors_accessor_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_ensemble_summary_provider_set_utils.py
  tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_history_vectors.py
  tests/unit_tests/utils_tests/test_ensemble_summary_provider_set/__init__.py
  tests/unit_tests/utils_tests/test_ensemble_summary_provider_set/mocks/ensemble_summary_provider_mock.py
  tests/unit_tests/utils_tests/test_ensemble_summary_provider_set/test_ensemble_summary_provider_set.py
  webviz_subsurface/_figures/timeseries_figure.py
  webviz_subsurface/_utils/ensemble_summary_provider_set.py
  webviz_subsurface/_utils/ensemble_summary_provider_set_factory.py
  webviz_subsurface/plugins/_bhp_qc.py
  webviz_subsurface/plugins/_parameter_analysis/_utils/__init__.py
  webviz_subsurface/plugins/_parameter_analysis/_utils/datetime_utils.py
  webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
  webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
  webviz_subsurface/plugins/_prod_misfit/_plugin.py
  webviz_subsurface/plugins/_prod_misfit/utils/make_dataframes.py
  webviz_subsurface/plugins/_prod_misfit/views/_production_misfit_per_real.py
  webviz_subsurface/plugins/_prod_misfit/views/_well_production_coverage.py
  webviz_subsurface/plugins/_prod_misfit/views/_well_production_heatmap.py
  webviz_subsurface/plugins/_property_statistics/controllers/property_response_controller.py
  webviz_subsurface/plugins/_simulation_time_series/_plugin.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_ensembles.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_resampling_frequency.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_utils/__init__.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_utils/delta_ensemble_utils.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_utils/derived_ensemble_vectors_accessor_utils.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_utils/ensemble_summary_provider_set_utils.py
  webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_view.py
Labels: enhancement 🚀, next release 🚢

#1171 Bugfix in `WellAnalysis`
  CHANGELOG.md
  webviz_subsurface/plugins/_well_analysis/_utils/_ensemble_well_analysis_data.py
Labels: next release 🚢

#1158 Remove `deck.gl` bounds and use only relevant ensembles in CO₂ plugin
  CHANGELOG.md
  webviz_subsurface/plugins/_co2_leakage/_plugin.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
  webviz_subsurface/plugins/_co2_leakage/views/mainview/mainview.py
Labels: bug 🐛, next release 🚢

#1168 Add reverse color tables to CO₂ plugin
  webviz_subsurface/plugins/_co2_leakage/_plugin.py
  webviz_subsurface/plugins/_co2_leakage/_utilities/color_tables.py
Labels: next release 🚢
